### ISSUE TITLE
Lower requirements from Wagtail 2.4 to 2.3.

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/django-kdl-wagtail#1]
I'm trying to install this package on a project that is held back to wagtail 2.3 due to other dependencies (puput) but the setup.py requirement is wagtail>=2.4 and the migrations fail because they depend on latest migrations in 2.4.

I'm planning to relax the requirements and test the package on a working 2.4 site (Field).

**Comment by jmiguelv** [comment]
`install_requires` in `setup.py` should also change to `wagtail>=2.3`.

**Comment by geoffroy-noel-ddh** [comment]
Well spotted, I'm sure I did modify it, probably in another copy of the package! Haven't found a nice way to make pipenv deal properly with sub-package in my dev env.
