### ISSUE TITLE
Selective Page type availability

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/django-kdl-wagtail#11]
I'd like to prevent some page types from being created by Wagtail editors on a project. That could be because I have another type of page in that project or simply because some core page types are not necessary (yet).

Could we add a mechanism to hide some pages types from Wagtail Create New Child Page based on custom and optional variable in settings.py?

**Comment by jmiguelv** [comment]
Yes, that is possible. I did it for egomedia by removing the parent page types and subpage types for the pages that should be hidden. It could be adapted to run from settings and/or a hook.
