### ISSUE TITLE
Display pagination only when needed

### ISSUE THREAD

**Issue by ginestra** [kingsdigitallab/django-kdl-wagtail#6]
* Django KDL Wagtail version: 0.7.3
* Django version: 2.1.7
* Python version: 3.5.2
* Operating System: Ubuntu

### Description
It would be good to display the pagination (includes/pagination.html) only when there is more than one page available (i.e. the list of items exceeds the one set in settings).

### What I Did

The existing template could be wrapped in 
```
{% if items.paginator.num_pages > 1 %}
...
{% endif %}
```
See: [https://github.com/kingsdigitallab/egomedia-django/blob/design/templates/kdl_wagtail_core/includes/pagination.html](https://github.com/kingsdigitallab/egomedia-django/blob/design/templates/kdl_wagtail_core/includes/pagination.html)

**Comment by jmiguelv** [comment]
Implemented by [d77f10e](https://github.com/kingsdigitallab/django-kdl-wagtail/commit/d77f10e4f7926651e9db54a1c7659bd4168852c9).
